global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # - job_name: "localhost" # if want to pull directly from app, without otel collector, use host machine IP (eg:192.168.4.170)
  #  scrape_interval: 5s
  #  static_configs:
  #    - targets: ["192.168.4.170:9464"]
  - job_name: 'otelColl'
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:8888'] # scrapes metrics of OTel collector from collectors :8888/metrics endpoint
  - job_name: 'demo'
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:8889'] # scrapes metrics of apps from OTel collectors :8889/metrics endpoint
